# Metadata
site_name: VVSPY 🚆
site_description: API Wrapper for VVS (Verkehrsverbund Stuttgart)
site_author: Zaanposni
repo_name: vvspy
repo_url: "https://github.com/zaanposni/vvspy"
watch: ["vvspy", "docs", "mkdocs.yaml", "pyproject.toml", "README.md"]

# Navigation
nav:
  - Getting Started: index.md
  - VVSPY:
      - Introduction: vvspy/index.md
      - Functions: vvspy/functions.md
      - Models: vvspy/models.md
      - Utilities: vvspy/utils.md
  - Examples: examples.md
  - Help: help.md
  - License: license.md

# Plugins
plugins:
  - search
  - git-revision-date-localized:
      fallback_to_build_date: true
  - autorefs
  - mkdocstrings:
      handlers:
        python:
          paths: [vvspy]
          import:
            - https://docs.python.org/3/objects.inv
            - https://mkdocstrings.github.io/objects.inv
            - https://mkdocstrings.github.io/griffe/objects.inv
          options:
            filters: ["!^__"]
            docstring_style: numpy
            docstring_section_style: table
            merge_init_into_class: true
            show_root_heading: true
            show_source: yes
            show_root_full_path: no

# Theme
theme:
  name: material
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

  features:
    # Enable the tabs on the top of the page (the level 1 folder will be displayed as a tab)
    - navigation.tabs

    # Will expand the navigation tree on the sidebar
    # - navigation.expand

    # TODO: Add description
    - navigation.tracking

    # Adds a button to get back to the top of the page
    - navigation.top

    # Shows files and navigation items on the left side
    - toc.integrate

    # TODO: Add description
    - search.suggest
    - search.highlight
    - content.tabs.link

  icon:
    logo: logo
    repo: fontawesome/brands/github

  language: en

# Extras
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/zaanposni/vvspy
      name: GitHub (zaanposni/vvspy)

# Markdown extensions
markdown_extensions:
  - attr_list
  - pymdownx.highlight:
      linenums: true
  - pymdownx.superfences
  - pymdownx.magiclink
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
